### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by sgn95** [charlesconnell/AudioCompare#6]
centos: 7
python: 2.7
numpy: 1.7.1-13.el7

exec :  ./audiomatch -f 11299.mp3 -f 10010.mp3
ERROR: [Errno 2] No such file or directory
ERROR: [Errno 2] No such file or directory

But The files are in the current folder

**Comment by sgn95** [comment]
replace WAV file
./audiomatch -f 11317.wav -f 11323.wav
not output

**Comment by sgn95** [comment]
Looking forward to your reply

**Comment by user-110** [comment]
> Looking forward to your reply

Hi, sgn,

to run a Python program, you have to use the main function.
i.e.: cd to the direction where you've cloned this project, then type in 'python main.py -f A.wav -f B.wav'
And everything is OK.

**Comment by sgn95** [comment]
thank you

**Comment by sgn95** [comment]
hello  i exec "python main.py -f A.wav -f B.wav" but console nothing

**Comment by sgn95** [comment]
Console has no output

**Comment by user-110** [comment]
> hello i exec "python main.py -f A.wav -f B.wav" but console nothing

Two questions:
1. Did you actually have wave files named 'A.wav' and 'B.wav' in that direction? 
    If not, try putting your wave files into the corresponding repository.
2. Is your default version of Python 2.x or 3.x? 
    If it is 3.x, you have to specify: 'python2 main.py -f A.wav -f B.wav'.

**Comment by sgn95** [comment]
wav file in Under the current folder
Where should I put the audio files?
python version 2.7.12

**Comment by user-110** [comment]
> wav file in Under the current folder
> Where should I put the audio files?
> python version 2.7.12

A quick way is to put them into the directory of your main.py file.
Remember to cd to the directory where the main function locates.

**Comment by WestbrookZero** [comment]
![20200421144950](https://user-images.githubusercontent.com/13358789/79834350-81fcde80-83df-11ea-8415-656aed10ccfa.png)
 cd to the directory,I put wav file and mp3 file into the main function locates,and python is 2.7,but still No such file or directory,please help.

**Comment by just4cn** [comment]
If ensure the file exists and still show this error, it may be that lame not suitable for current system.
You can test with enter `./lame` in the root path of project, if it show `/lib/ld-linux.so.2: bad ELF interpreter: No such file or directory`, you will need reinstall lame with `yum install lame`(**centos**) and replace the lame with installed one:

```
which lame
# output: /usr/bin/lame
# remove current lame
rm ./lame
# copy installed lame to current path
cp /usr/bin/lame ./
```

OR

change InputFile.py `lame = os.path.dirname(os.path.abspath(__file__)) + "/lame"` to `lame = '/usr/bin/lame'`

**Comment by charlesconnell** [comment]
Thanks all for the helpful conversation here. It sounds like this is not an actual bug, so I'm going to close the ticket.
