### ISSUE TITLE
Exec format error

### ISSUE THREAD

**Issue by adon988** [charlesconnell/AudioCompare#7]
Mac
Python 2.7.10
numpy      1.16.4

./audiomatch -f a.mp3 -f b.mp3
ERROR: [Errno 8] Exec format error
ERROR: [Errno 8] Exec format error

./audiomatch -f ability.wav -f ability.wav
ERROR: [Errno 8] Exec format error
ERROR: [Errno 8] Exec format error

python main.py -f backward.wav -f ability.wav
ERROR: [Errno 8] Exec format error
ERROR: [Errno 8] Exec format error

Help!

**Comment by adon988** [comment]
Finally, I use Ubuntu and success. ~

**Comment by SeanTong11** [comment]
Same problem.But I ran it in Debian10.

**Comment by SeanTong11** [comment]
> Same problem.But I ran it in Debian10 arm.

Problem solved,the wav file I used somehow don't work with this program.If  someone has the same problem like me,I recomend you to change your audio file.

**Comment by charlesconnell** [comment]
This is because the MP3 converter which is included only works on Linux.
